### ISSUE TITLE
With WebSockets, door becomes "unavailable" on unlock or ring (on 1.1.1)

### ISSUE THREAD

**Issue by ethank** [imhotep/hass-unifi-access#10]
Rather than showing it unlocked, or showing a doorbell press, the device becomes "unavailable" which makes it impossible to trigger actions.

**Comment by imhotep** [comment]
@ethank unfortunately, the lock entity has to be made unavailable when unlocking because locking is currently unsupported by the API and leaving it active caused all sorts of issues. What kind of trigger are you using? Do you have a DPS installed?

The doorbell press has a separate **binary_sensor** that becomes **true** while the doorbell is ringing, **false** otherwise.

**Comment by techunleadit** [comment]
@ethank do you mean the device lock.device_name?

@imhotep I don't see this problem, but I'm using Access version 1.22.10, maybe it's been fixed?

**Comment by imhotep** [comment]
@ethank I am going to close this as there is no way to disable the lock entity without causing other issues. The doorbell press has its own binary_sensor and the API does not support locking a door so have to make it unavailable while unlocked.
If there are specific automations you have in mind, I am happy to help wit those.
