### ISSUE TITLE
New Feature form API?

### ISSUE THREAD

**Issue by aLAN-LDZ** [imhotep/hass-unifi-access#44]
Can You add set emergency mode?

![image](https://github.com/imhotep/hass-unifi-access/assets/33158372/47d38497-e91b-4ea9-bded-6a46f9508b09)

or set temporary door locking rule? to stay on lock/unlock status?

![image](https://github.com/imhotep/hass-unifi-access/assets/33158372/16b1c833-c0a0-4bb1-b29d-7db445db4c31)

**Comment by aLAN-LDZ** [comment]
First of all, thanks for your answer. I tried to fork and add options myself, but it's not my level yet :P

I was thinking about making two switches for Emergency Status

One set to true does evacuation, the other set to true does lockdown. Set to false disables this mode.

However, the Temporary Door Locking Rule, I don't really know how. I would like, or rather my wife ;) who is dissatisfied that she has to unlock the door with a card/PIN during the day, to be able to set the automation so that if someone is at home - leave it unlocked

**Comment by imhotep** [comment]
@aLAN-LDZ I've been playing around with this and I was able to add switches to the integration:
![evacuation_lockdown](https://github.com/user-attachments/assets/67a904a3-0c45-4e43-a518-79b590418b52)

However, I did notice that every time I hit either evacuation or lockdown, it will sound the alarm. No matter what the alarm setting is (even if it's set to never go off). Is this something you really want?

Also right now, it's polling for evacuation and lockdown status every 3 seconds. Since the websocket API is not documented I'd have to dig in and see if we do get emergency updates via websockets to avoid polling too much.

**Comment by aLAN-LDZ** [comment]
Generally, I need an option that will be able to leave the door in the "leave open" status, maybe the 7.10 API option will be better. I just found two examples. I looked at how they work on the UI website

**Comment by imhotep** [comment]
Gotcha. So definitely not evacuation and lockdown then. The door locking rule adds some challenges from an interface standpoint. I am unsure if we should be using an `input_select` or a `service` call. `input_select` (basically a dropdown) may be better for ease of use but then that adds challenges for custom locking mode which requires an interval.

**Comment by aLAN-LDZ** [comment]
basically a dropdown seems like a better idea, if i could help somehow let me know.

**Comment by imhotep** [comment]
@aLAN-LDZ can you try this [branch](https://github.com/imhotep/hass-unifi-access/pull/49) and let me know if it works for you?

**Comment by aLAN-LDZ** [comment]
Yes, it works great, thank you.
I tested all settings.

**Comment by imhotep** [comment]
Check out v1.2.0
