### ISSUE TITLE
Doorbell State Not Updating

### ISSUE THREAD

**Issue by MattHadfield113** [imhotep/hass-unifi-access#52]
Doorbell status is not adjusting when pressed on the UI-Intercom.

Happy to test any new versions that fix this as understand you might not have the hardware available.

[access_log.txt](https://github.com/user-attachments/files/16430337/access_log.txt)

**Comment by imhotep** [comment]
@MattHadfield113 there is initial [support](https://github.com/imhotep/hass-unifi-access/pull/49) for the UGT and the UAH-Ent. Indeed, I don't have the UI-Intercom but may be able to add support for it. We will just need some additional logging. I am hoping to release a new version in the next few days that will have more helpful logs. I will update you when it's out.
Just FYI though, the current doorbell status is very finicky (even with the Unifi Access Hub) as the API doesn't really provide a clean way of knowing status.

**Comment by fieldsalad2** [comment]
@imhotep would Doorbell Status have been finicky since around 2 months now? If so that explains why automations were working perfectly up until then and have been very hit and miss since... (more miss than hit).
For me this means that currently, someone ringing the doorbell (G2) is no longer triggering the Sonos system to ring the doorbell. I've narrowed it down to the Doorbell event not being registered properly.
Would this be related? Any workarounds?

**Comment by fieldsalad2** [comment]
@imhotep Thank you for your reply; I have registered a new Issue.
Apologies for temporarily hijacking your Issue @MattHadfield113 , that was not the intention :)

**Comment by imhotep** [comment]
@MattHadfield113 if you could try v1.2.0 in debug mode and share some logs here. We may be able to add support for the intercom

**Comment by imhotep** [comment]
@MattHadfield113 thanks for this. It looks like your hub is similar to the Unifi Access Hub. However, in those logs you shared, I am only seeing the doorbell cancelation message not the doorbell start message which would explain why you're not seeing state updates. 2 reasons for this:
1) Your hub is not sending that information
2) Your logs don't include that information because it either happened earlier (before your started logging) or it never happened.

Did you start logging BEFORE pressing the doorbell?

**Comment by imhotep** [comment]
@MattHadfield113 closing this for now. Feel free to re-open if you're still facing issues.
