### ISSUE TITLE
Integration w/ UID - Promise I read it didn't work

### ISSUE THREAD

**Issue by martinkwright** [imhotep/hass-unifi-access#53]
I certainly acknowledge the **"If you have Unifi Access set up with UID this will NOT work."** 

BUT, if Unifi has enabled your UID site for API access, could this integration work? Reaching out to the site address w/ the token vs local?

**Comment by imhotep** [comment]
@martinkwright I have no idea. If the API is exactly the same, I don't see a reason why it would not work. This (local) integration uses an API endpoint and access token. Assuming UID uses a remote endpoint and an access token, it should work? Perhaps try and let me know :) ?

**Comment by 123gizi** [comment]
I'm using the integration at the same time as the free version of UID without any issues.

I don't know if it's my API settings, but I don't get details for the access log in HA, just that it was accessed. This could be because my API Token only allows permission to "View" Space, Device and System Log with other permissions set to "None".

@imhotep Thanks for building this integration, it works perfectly for what I need!

**Comment by imhotep** [comment]
@123gizi thanks for reporting that! I usually give full access so I am not sure which granular permissions are required for this integration to work. I will try to find those and add them to the documentation.

@martinkwright looks like you have your answer. 

I will also try migrating to UID and update the docs if everything works

**Comment by martinkwright** [comment]
Appreciate it!

**Comment by martinkwright** [comment]
> @martinkwright I have no idea. If the API is exactly the same, I don't see a reason why it would not work. This (local) integration uses an API endpoint and access token. Assuming UID uses a remote endpoint and an access token, it should work? Perhaps try and let me know :) ?

Will give a try this week.
